spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user_test
    password: user
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: mybatis/*/**.xml
  type-aliases-package: me.donghyun.calendar.mapper
